version: '3'
services:
    web:
      build: .
      ports:
        - 5000:5000
      environment:
        - SECRET_KEY="123123"
        - REDIS_PORT=6379
        - MONGO_PORT=27017
      depends_on:
        - mongo
        - redis
    mongo:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb_data:/var/lib/mongodb/data
    redis:
      image: redis
      ports:
        - 6379:6379
      volumes:
        - redis_data:/data
volumes:
    mongodb_data:
    redis_data:
